### ISSUE TITLE
Зауваження

### ISSUE THREAD

**Issue by samaranin** [Paniov-M/Snake1#1]
Draw - порожній
Input - порожній
Logik - порожній
Main - порожній
Ну і Source.cpp нема, а він імпортується :)
Взагальному - пробуй ще
https://github.com/Masum58/Algorithm/blob/master/SnckGame.cpp

**Comment by Paniov-M** [comment]
виправив

**Comment by samaranin** [comment]
`#include "Source.cpp"`
Досі не бачу цього файла в репозиторії.
А він імпортується не в одному файлі.
Без нього, я так розумію, програма не запуститься.

**Comment by samaranin** [comment]
Ну і відстуня інструкція із скріншотами.
